# Generated by Django 5.2 on 2025-05-01 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_forumcategory_forumtopic_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumtopic',
            name='last_active',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
