# Generated by Django 5.2 on 2025-09-02 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_forumtopic_last_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumtopic',
            name='description',
            field=models.TextField(default='No text provided.'),
        ),
    ]
