# Generated by Django 5.2 on 2025-04-28 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='current_members',
            field=models.IntegerField(default=0),
        ),
    ]
