# Generated by Django 5.2 on 2025-08-19 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_skill_projectrequiredskill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectmembership',
            old_name='joined_at',
            new_name='joined_date',
        ),
    ]
