# Generated by Django 5.2 on 2025-08-30 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github_repository_url',
            field=models.URLField(blank=True, null=True, verbose_name='GitHub Repository URL'),
        ),
    ]
