# Generated by Django 5.2 on 2025-08-31 00:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_projectfile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('activity_type', models.CharField(choices=[('member_joined', 'Member Joined'), ('member_left', 'Member Left'), ('chat_message', 'Chat Message'), ('whiteboard_updated', 'WhiteBoard Updated'), ('task_created', 'Task Created'), ('task_deleted', 'Task Deleted'), ('task_edited', 'Task Edited'), ('task_status_updated', 'Task Status Updated'), ('file_uploaded', 'File Uploaded')], max_length=50)),
                ('details', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='accounts.project')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
